### ISSUE TITLE
Add an enum for command arguments

### ISSUE THREAD

**Issue by ConradMS** [CSC207-UofT/course-project-stress_coders#28]
Currently command args are hardcoded, change it so there is a enum of command args like

THROW_TARGET("target").

etc.

**Comment by riyanah** [comment]
Would this be an example of what you mean:

 in axe, there is a howToUse string which tells it how to use the weapon , and its hard coded to be "throw: thrown_obj=axe1, target=enemy1".  howToUse is from the Interactable class. 

So instead we would use enums instead of hard coding "throw: thrown_obj=axe1, target=enemy1".?

**Comment by riyanah** [comment]
Or do u mean this part
`    public static void loadCommands(){
        COMMANDS.put("talk_to", new TalkTo());
        COMMANDS.put("throw", new Throw());
        COMMANDS.put("chop", new Chop());
        COMMANDS.put("consume", new Consume());
    }`

in CommandConstants

**Comment by riyanah** [comment]
This issue was fixed with the additin of interfaceadapters PR #87 and PR #88
