### ISSUE TITLE
Response system

### ISSUE THREAD

**Issue by shehzaad777** [CSC207-UofT/course-project-stress_coders#6]
There is currently no response system in place. For instance, if an enemy were to damage a player, would Enemy directly damage player or would we delegate this to an executor manager class. My proposed solutions are either 1) We create a Response class that every interaction will return and will have properties such as player_needs_update and so on which can be seen and dealt with in a manager class that has access to all needed instances or 2) The Enemy class and other classes will have access to relevant classes that do not break clean architecture patterns. For now, I will use option 2 and we can discuss this further (simple edits to make)

**Comment by devan-srinivasan** [comment]
Yea I observed that too. Building off of your idea, I think we should use an `Interaction` class that defines an interaction between two parties. For example, an interaction between a Player throwing an Axe at an Enemy would instantiate an `Interaction(parties={player1, enemy1}, params={axe1})` and how this is used will depend on the GameObject that is responding. For example, in the current throwing system we have, `Enemy.handleHit()` is called in the throw command through the arbitrary call of `handleHit` as defined by the Hittable interface. Here, in addition to what is already passed in, we can pass in the new Interaction Object. That way each gameobject can respond in their own way, and this would be delegated in the responder rather than in the GameState in some logic structure as you have suggested. Nonetheless all are good ideas. One of us will surely be able to resolve this.

> There is currently no response system in place. For instance, if an enemy were to damage a player, would Enemy directly damage player or would we delegate this to an executor manager class. My proposed solutions are either 1) We create a Response class that every interaction will return and will have properties such as player_needs_update and so on which can be seen and dealt with in a manager class that has access to all needed instances or 2) The Enemy class and other classes will have access to relevant classes that do not break clean architecture patterns. For now, I will use option 2 and we can discuss this further (simple edits to make)
